version: '3'
services:
  db:
    image: postgres:15.3
    container_name: car-fleet_db
    ports:
      - 5432:5432
    volumes:
      - ./docker_vol/postgres:/var/lib/postgresql/data
    env_file:
      - ${CAR_FLEET_ENV:-.env}
    networks:
      - car-fleet
    restart: unless-stopped
  back:
    build: .
    image: paketobuildpacks/spring-boot
    container_name: car-fleet_back
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - ${CAR_FLEET_ENV:-.env}
    networks:
      - car-fleet
    restart: unless-stopped
networks:
  car-fleet:
volumes:
  db:
